name: first Job
on : push

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: OIDC AWS configure
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::977727482222:role/S3-OIDC-gitactions"
          role-session-name: "github-actions"
          aws-region: ap-south-1

      - name: Static code to s3 bucket
        run: |
          aws s3 sync ./ s3://navaneetha-s3-bucket/ \
          --exclude "*" \
          --include "*.html"

      
   